[package]
name = "BotDev"
version = "0.1.0"
authors = ["gambl3r08 <robertojoselozada@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telebot=""